name: Run Fractal Script

on:
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Adjust as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy

    - name: Run Fractal Script
      run: |
        python scripts/script1.py
