name: Run Python Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add other dependencies here if needed

    - name: Run the script
      run: |
        python scripts/script1.py
